name: GitHub CI

on:
  push:
    branches: [  stl-testing ]
  pull_request:
    branches: [  stl-testing ]

jobs:
  debug:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build debug
      run: |
         mkdir -p build/run
         cd build/run
         cmake ../..
         make install
         cd ../..
         ./bin/stltest


